preset: laravel

enabled:
  - alpha_ordered_imports
  - concat_with_spaces

disabled:
  - length_ordered_imports
  - concat_without_spaces
  - trailing_comma_in_multiline_array
  - phpdoc_summary

finder:
  exclude:
    - "tests"
    - "node_modules"
    - "storage"
    - "vendor"
  not-name:
    - "AcceptanceTester.php"
    - "FunctionalTester.php"
    - "UnitTester.php"